baseURL = 'https://cs61a.rouxl.es/'
languageCode = 'en-us'
title = 'CS61A Notes'
theme = "book"
publishDir = "docs"
enableGitInfo = true
googleAnalyticsID = "G-QB72X4S5RZ" 

[params]

    BookTheme = 'auto'
    BookRepo = 'https://github.com/Rouxles/cs61a-notes/'